name: build
on:
  push:
permissions: {}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - run: corepack pnpm install
      - run: corepack pnpm run build
      - name: Check code style
        run: corepack pnpm run lint && git diff --exit-code
